// <auto-generated />
namespace CodeFirstDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class publisher_contact_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(publisher_contact_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201811211431342_publisher_contact_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
